# Generated by Django 5.0.2 on 2024-02-27 19:23

import words.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_word', models.CharField(default=None, max_length=100)),
                ('rus_translation', models.CharField(default=None, max_length=255)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to=words.models.audio_file_name)),
                ('support_word', models.JSONField(blank=True, default=dict, null=True)),
                ('explanations', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
