# Generated by Django 5.0.2 on 2024-02-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='how_to_memorize',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
